pupil_mask:

  # Home positions
  zaber_h_home: 189390, # Horizontal axis home position (steps)
  zaber_v_home: 157602, # Vertical axis home position (steps)
  newport_home: 56.3    # Angle of the pupil mask n°1 (degree)

  # On which ports the components are conencted
  zaber_port: "/dev/ttyUSB0"
  newport_port: "/dev/ttyUSB1"

