name: 🐍 Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install project dependencies
        run: pdm install

      - name: Build package
        run: pdm build

      - name: Publish to PyPI
        env:
          PDM_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: pdm publish --username __token__ --password $PDM_PYPI_TOKEN
